# in case of  express backend we dont required to communicate 
# database at image build time 

FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./package.json ./package.json 
COPY ./bun.json ./bun.json 

COPY .package-lock.json ./package-lock.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install
RUN bun run db:migrate

EXPOSE 8080

CMD [ "bun", "run", "start:backend" ]