name : Deploy the backend

on: 
  push : 
   branches: [main]

jobs:
  build: 
    run-on: ubuntu-latest
    steps:
     - name: copy the repo on git machine 
       uses: actions/checkout@v2

     - name: Docker login 
       uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Build and push 
       uses: docker/build-push-action@v4
       with:
        context: .
        file: ./Docker/Dockerfile.backend
        push: true
        tags: chiragshrimal/todo-app-backend:${{ github.sha }}


     
